export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_TAG = "FILTER_PRODUCTS_BY_TAG";
export const UPDATE_PRODUCT_COUNT = "UPDATE_PRODUCT_COUNT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
